# Generated by Django 4.1.3 on 2023-03-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userbase_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
