# Generated by Django 4.1.3 on 2023-03-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, default='Responsive image', help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
    ]
