# Generated by Django 4.1.3 on 2023-03-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_users_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_homepage',
            field=models.BooleanField(default=True, verbose_name='Zobrazit na domovské stránce'),
        ),
    ]
